### ISSUE TITLE
It seems the font doesn't contain `💤`

### ISSUE THREAD

**Issue by zwyyy456** [Karmenzind/monaco-nerd-fonts#8]
The character becomes a square when I use layz vim.

**Comment by Karmenzind** [comment]
@zwyyy456 Hi
I pasted this character in alacritty and gvim:
![image](https://user-images.githubusercontent.com/17923071/226209028-de886341-598b-43cd-8cf9-019488e62568.png)
![image](https://user-images.githubusercontent.com/17923071/226209071-ce3f0f88-6a7b-4ed0-8520-362c9b38889d.png)
Maybe this problem is caused by layz vim itself. Have you ever tried other program?
